### ISSUE TITLE
Why needn't we also do 'pitch convert' when doing 'rhythm conversion'?

### ISSUE THREAD

**Issue by XintaoZhao0805** [biggytruck/SpeechSplit2#2]
from the demo.ipynb

if 'R' in cond:
            inp_rhy = tgt_rhy
if 'U' in cond:
            inp_tim = tgt_tim
if 'F' in cond:
            inp_pit = convert_pit(F, src_rhy, tgt_con, tgt_pit)

and the paper said the reason we need a pitch converter is to align the temporal mismatched information in pitch and rhythm.
But When we are doing rhythm conversion , the mismatch still exsist.
Why shouldn't we also do pitch conversion in rhythm conversion?

By the way , im also confusing why the pitch convertor could be trained successfully. It seems to feed the pitch information and force the converter to predict pitch itself. Why the converter could learn the alignment information?

i have read speechsplit 1.0 , the question above still confusing me

**Comment by biggytruck** [comment]
According to the "fill in the blank" mechanism, the rhythm code alone is sufficient to provide rhythm information, e.g., how long each syllabus/pauses should be, while the pitch needs to align with the rhythm to determine the tone of each syllable
