### ISSUE TITLE
Contribution: Inference notebook

### ISSUE THREAD

**Issue by freds0** [biggytruck/SpeechSplit2#4]
Following is the link to access a jupyter notebook inference running on google colab

[https://colab.research.google.com/drive/1ltljcJV_ZCejUIKwDj0nshtS9KSSrXtK?usp=sharing](https://colab.research.google.com/drive/1ltljcJV_ZCejUIKwDj0nshtS9KSSrXtK?usp=sharing)

I hope it helps anyone interested.

**Comment by ehsienmu** [comment]
Hello, because all the links to the pre-trained models are broken. I would like to ask if you have the pre-trained file? Thank you.
