### ISSUE TITLE
Some thing wrong in your data_processing.py

### ISSUE THREAD

**Issue by yangdongchao** [biggytruck/SpeechSplit2#6]
Hi, I try to use your data_processing.py file to extract features, but I find the code only save the last file in one speaker file, e.g. It only save p225_366 in p225 speaker. Because you use the variable filename is a global variable.

**Comment by biggytruck** [comment]
Which line are you referring to?

**Comment by yangdongchao** [comment]
> Which line are you referring to?

line 87   filename

**Comment by biggytruck** [comment]
`filename` is an element of `file_list` which should be a list of audio files. The code works well for me. Did you save your data like this?
```
  data
    |__train
    |    |__P225
    |        |__wavfile1
    |        |__wavfile2
    |        ...
    |    |__P226
    |     ...
```

**Comment by yangdongchao** [comment]
> 

Yes, I save it like this.
Now, I have solve the problem, by change the code in line 58: for idx, (wav, f0, sp, ap) in enumerate(zip(wavs, f0s, sps, aps)) to
for idx, (filename, wav, f0, sp, ap) in enumerate(zip(file_list, wavs, f0s, sps, aps)):
