### ISSUE TITLE
The mismatch between training and inference.

### ISSUE THREAD

**Issue by yangdongchao** [biggytruck/SpeechSplit2#7]
Hi, I read your code, in the training stage, you use the vtlp method to corrupt the timbre information, but in our demo.ipynb, you donot use vtlp, why?

**Comment by biggytruck** [comment]
By applying VTLP during training, all 3 encoders learn to discard the timbre information and only focus on extracting the information they are supposed to learn(rhythm, content, pitch). Thus during inference, each encoder is capable of ignoring the timbre info even without VTLP

**Comment by yangdongchao** [comment]
> 

OK, thanks for your help, I understood it.

**Comment by SeptemberN** [comment]
@yangdongchao 
Hello! Do you have a backup of all pre-trained models? All the Google Cloud Disk links provided by the author have expired
